dom = User.create(username: "ddeleon267", email: "ddeleon267@test.com", password: "password1")
nicole = User.create(username: "domtastic1", email: "domtastic1@test.com", password: "password2")
nikki = User.create(username: "dominique", email: "dominique@test.com", password: "password3")

# Routine.create(name: "Fall Morning", products: "Some Products", description: "Some description", user_id: 1)
# Routine.create(name: "Fall Morning2", products: "Some Products2", description: "Some description2", user_id: 2)
# Routine.create(name: "Fall Morning3", products: "Some Products3", description: "Some description3", user_id: 3)
# Routine.create(name: "Fall Evening", products: "Some Products", description: "Some description", user_id: 1)
# Routine.create(name: "Fall Evening", products: "Some Products2", description: "Some description2", user_id: 2)
# Routine.create(name: "Winter Morning", products: "Some Products3", description: "Some description3", user_id: 1)
#
# Product.create(name: "Gentle Cleanser A", type: "Cleanser", ingredients: "Some ingredients", notes: "Appropriate pH" )
# Product.create(name: "Gentle Cleanser B", type: "Cleanser", ingredients: "Some ingredients", notes: "Appropriate pH" )
# Product.create(name: "Gentle Cleanser C", type: "Cleanser", ingredients: "Some ingredients", notes: "Appropriate pH" )
# Product.create(name: "Lightweight Moisturizer A", type: "Moisturizer", ingredients: "Some ingredients", notes: "Silicone free" )
# Product.create(name: "Lightweight Moisturizer B", type: "Moisturizer", ingredients: "Some ingredients", notes: "Some essential oils" )
# Product.create(name: "Lightweight Moisturizer C", type: "Moisturizer", ingredients: "Some ingredients", notes: "Feels like nothing" )
# Product.create(name: "Heavy Moisturizer A", type: "Moisturizer", ingredients: "Some ingredients", notes: "Great occlusive" )
# Product.create(name: "Heavy Moisturizer B", type: "Moisturizer", ingredients: "Some ingredients", notes: "Not recommended for acne-prone skin" )
# Product.create(name: "Heavy Moisturizer C", type: "Moisturizer", ingredients: "Some ingredients", notes: "Dries down matte" )
# Product.create(name: "Toner A", type: "Toner", ingredients: "Some ingredients", notes: "Very Moisturizing" )
# Product.create(name: "Toner B", type: "Toner", ingredients: "Some ingredients", notes: "Not astringent at all" )
# Product.create(name: "Toner C", type: "Toner", ingredients: "Some ingredients", notes: "Tingles a little" )
# Product.create(name: "Chemical Sunscreen", type: "Sunscreen", ingredients: "Some ingredients", notes: "Strong fragrance" )
# Product.create(name: "Physical Sunscreen", type: "Sunscreen", ingredients: "Some ingredients", notes: "Minimal white cast" )
# Product.create(name: "Combination Sunscreen", type: "Sunscreen", ingredients: "Some ingredients", notes: "Not greasy at all" )
#
# RoutineProduct.create(routine_id: 1, product_id: 1)
# RoutineProduct.create(routine_id: 2, product_id: 2)
# RoutineProduct.create(routine_id: 3, product_id: 3)
# RoutineProduct.create(routine_id: 1, product_id: 4)
# RoutineProduct.create(routine_id: 2, product_id: 5)
# RoutineProduct.create(routine_id: 3, product_id: 6)
# RoutineProduct.create(routine_id: 4, product_id: 7)
# RoutineProduct.create(routine_id: 5, product_id: 8)
# RoutineProduct.create(routine_id: 6, product_id: 9)
# RoutineProduct.create(routine_id: 1, product_id: 10)
# RoutineProduct.create(routine_id: 2, product_id: 11)
# RoutineProduct.create(routine_id: 3, product_id: 12)
# RoutineProduct.create(routine_id: 1, product_id: 13)
# RoutineProduct.create(routine_id: 2, product_id: 14)
# RoutineProduct.create(routine_id: 3, product_id: 15)
# RoutineProduct.create(routine_id: 4, product_id: 1)
# RoutineProduct.create(routine_id: 5, product_id: 2)
# RoutineProduct.create(routine_id: 6, product_id: 3)
# RoutineProduct.create(routine_id: 5, product_id: 4)
# RoutineProduct.create(routine_id: 1, product_id: 5)
# RoutineProduct.create(routine_id: 2, product_id: 6)
# RoutineProduct.create(routine_id: 6, product_id: 7)
# RoutineProduct.create(routine_id: 6, product_id: 8)
# RoutineProduct.create(routine_id: 4, product_id: 9)
# RoutineProduct.create(routine_id: 6, product_id: 10)
#
# dom.save
# nicole.save
# nikki.save
